/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Tommy' at '1/23/19, 3:35 PM' with Gradle 2.10
 *
 * @author Tommy, @date 1/23/19, 3:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
